### ISSUE TITLE
PuppeteerSharp.BufferException: 'Unable to get response body'

### ISSUE THREAD

**Issue by avifatal** [hardkoded/puppeteer-sharp#1378]
Hi,
 I am getting the error: `PuppeteerSharp.BufferException: 'Unable to get response body'` in the following line `var txt = await e.Response.TextAsync()` 
What may cause that?   
```
page.Response += async (object sender, ResponseCreatedEventArgs e) => {
  if (e.Response.Url.Contains(".json"))
  {
      var txt = await e.Response.TextAsync();
  }
```

It is happening randomly... I can't put my finger on it...
Thanks

**Comment by kblok** [comment]
@avifatal can you take a look at the InnerException?

**Comment by avifatal** [comment]
```
PuppeteerSharp.BufferException: Unable to get response body
 ---> PuppeteerSharp.MessageException: Protocol error (Network.getResponseBody): No data found for resource with given identifier
   at PuppeteerSharp.CDPSession.SendAsync(String method, Object args, Boolean waitForCallback)
   at PuppeteerSharp.CDPSession.SendAsync[T](String method, Object args)
   at PuppeteerSharp.Response.BufferAsync()
   --- End of inner exception stack trace ---
   at PuppeteerSharp.Response.BufferAsync()
   at PuppeteerSharp.Response.TextAsync()
   at EServices.Web.Services.Reader.PostReader.<>c__DisplayClass1_0.<<ScrapePosts>b__0>d.MoveNext() in C:\work\projects\e\e-server-new\EServices\EServices.Web\Services\Reader\PostReader.cs:line 35
```

**Comment by kblok** [comment]
It seems to be a Chromium side effect. See https://github.com/puppeteer/puppeteer/issues/2258 and https://medium.com/@jsoverson/using-chrome-devtools-protocol-with-puppeteer-737a1300bac0
