### ISSUE TITLE
Using Page object on a separate thread, when main thread is blocked

### ISSUE THREAD

**Issue by ReinisV** [hardkoded/puppeteer-sharp#1619]
**Before you file a bug, have you:**

* Tried upgrading to newest version of PuppeteerSharp, to see if your issue has already been resolved and released?
  * Created the repro code just now and installed newest package
* Checked existing open *and* closed [issues](https://github.com/kblok/puppeteer-sharp/issues?utf8=%E2%9C%93&q=is%3Aissue), to see if the issue has already been reported?
  * didn't find anything related to freezing or deadlocking tasks
* Tried reproducing your problem in a new isolated project?
  * yes
* Considered if this is a general question and not a bug?. For general questions please use [StackOverflow](https://stackoverflow.com/search?q=puppeteer-sharp).
  * due to the simple use case, feels like a bug to me
### Description

Creating a browser instance on the main thread and then opening new Pages on different threads (as created by Task.Run) and manipulating them makes some of the Tasks freeze.

Building the following Console app (in my case with VS2019) and running it (either in debug or directly from CMD) causes
```
Unhandled exception. System.TimeoutException: Timeout of 30000 ms exceeded
   at PuppeteerSharp.Helpers.TaskHelper.<>c__DisplayClass2_0.<WithTimeout>b__0()
   at PuppeteerSharp.Helpers.TaskHelper.WithTimeout(Task task, Func`1 timeoutAction, TimeSpan timeout, CancellationToken cancellationToken)
   at PuppeteerSharp.FrameManager.WaitForFrameNavigationAsync(Frame frame, NavigationOptions options)
```  
 
### Complete minimal example reproducing the issue

```csharp
using PuppeteerSharp;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace PuppeteerTaskDeadlockRepro
{
    class Program
    {
        static async Task Main(string[] args)
        {
            var browserFetcher = new BrowserFetcher();
            Console.WriteLine("fetching browser");
            await browserFetcher.DownloadAsync(BrowserFetcher.DefaultRevision);

            Console.WriteLine("launching browser");
            var browser = await Puppeteer.LaunchAsync
            (
                new LaunchOptions
                {
                    Headless = false
                }
            );

            var tasks = new List<Task<(string url, string contents)>>();
            var urls = new[] { "https://www.google.com", "https://www.stackoverflow.com", "https://www.github.com" };
            
            Console.WriteLine("starting parallel collection");
            foreach (var url in urls)
            {
                tasks.Add(GetPageHtmlAsync(browser, url));
            }

            var allContents = await Task.WhenAll(tasks.ToArray());
            Console.WriteLine("collection done");

            foreach (var (url, contents) in allContents)
            {
                Console.WriteLine($"{url} : {contents.Length}");
            }
        }

        private static Task<(string url, string contents)> GetPageHtmlAsync(Browser browser, string url)
        {
            return Task.Run(async () =>
            {
                Console.WriteLine($"{url} : opening new page");
                var page = await browser.NewPageAsync();
                Console.WriteLine($"{url} : starting navigation");
                await page.GoToAsync(url);
                Console.WriteLine($"{url} : waiting for navigation");
                await page.WaitForNavigationAsync();
                Console.WriteLine($"{url} : getting contents");
                var contents = await page.GetContentAsync();
                return (url, contents);
            });
        }
    }
}

```

### Expected behavior:

No errors to be thrown, pages sucessfully downloaded and information outputted.

### Actual behavior:

Browser is opened, pages are opened, waiting for navigation tasks freeze:
![image](https://user-images.githubusercontent.com/10805335/106385311-5d0ab280-63d8-11eb-9afd-cd066130ebb2.png)
![image](https://user-images.githubusercontent.com/10805335/106385335-7b70ae00-63d8-11eb-81ea-3ebcf458380e.png)
![image](https://user-images.githubusercontent.com/10805335/106385322-672cb100-63d8-11eb-9cd8-5ec4be74ce13.png)

these are the tasks that are running when the Exception happens, if this gives you anything to go by:
![image](https://user-images.githubusercontent.com/10805335/106385354-93483200-63d8-11eb-89e9-5fb4e24c0bc8.png)

### Versions

* Which version of PuppeteerSharp are you using?
  * PuppeteerSharp 2.0.4
* Which .NET runtime and version are you targeting? E.g. .NET framework 4.6.1 or .NET Core 2.0.
  * .NET Core 3.1

**Comment by ReinisV** [comment]
Right after posting, noticed an error in my repro code, the `await page.WaitForNavigationAsync();` is not necessary when using `await page.GoToAsync(url);`, it is necessary when navigating only via buttons, which explains my tasks timing out.

Though I do feel I just wrote the repro code incorrectly, and I still have the issue in my main app. Oh well, will reopen when I can reproduce the issue I'm having on a smaller repro app.

**Comment by ReinisV** [comment]
ok, new repro here:

```c#
using PuppeteerSharp;
using System;
using System.Threading;
using System.Threading.Tasks;

namespace PuppeteerTaskDeadlockRepro
{
    class Program
    {
        static ManualResetEvent _quitEvent = new ManualResetEvent(false);

        static async Task Main(string[] args)
        {
            var browserFetcher = new BrowserFetcher();
            Console.WriteLine("fetching browser");
            await browserFetcher.DownloadAsync(BrowserFetcher.DefaultRevision);

            Console.WriteLine("launching browser");
            var browser = await Puppeteer.LaunchAsync
            (
                new LaunchOptions
                {
                    Headless = false
                }
            );

            Console.CancelKeyPress += (sender, eArgs) =>
            {
                Console.WriteLine("App killed");
                _quitEvent.Set();
                eArgs.Cancel = true;
            };

            RunIndefinitely(browser);

            _quitEvent.WaitOne();
            
            // cleanup code here
        }

        private static void RunIndefinitely(Browser browser)
        {
            var thread = new Thread(async () =>
            {
                while (true)
                {
                    await PrintPageInfo(browser);

                    await Task.Delay(TimeSpan.FromSeconds(5));
                }
            });
            thread.Start();
        }

        private static async Task PrintPageInfo(Browser browser)
        {
            var url = "https://www.google.com";

            Console.WriteLine("opening new page");
            var page = await browser.NewPageAsync();
            Console.WriteLine("starting navigation");
            await page.GoToAsync(url);
            Console.WriteLine("waiting for navigation");
            var contents = await page.GetContentAsync();
            Console.WriteLine($"{url} : {contents.Length}");
        }
    }
}

```

I guess this now becomes more of a question than a bug, but still. 

How should I go about blocking the main thread while I have Puppeteer executing on other threads (doesnt really matter, if started via Task.Run or any other way) without causing a deadlock?

this example blocks on the `browser.NewPageAsync()` Task with a similar Task list:
![image](https://user-images.githubusercontent.com/10805335/106386642-9b0ad500-63de-11eb-8d2f-6ec9cc0fbc8d.png)

Even though I'm blocking on the main thread I would expect the thread created in `RunIndefinitely(Browser browser)` to still be spinning.

**Comment by ReinisV** [comment]
It seems that creating the browser instance on a separate thread (that you don't block) solves the blocking issue of this specific bug reproduction:
```C#
using PuppeteerSharp;
using System;
using System.Threading;
using System.Threading.Tasks;

namespace PuppeteerTaskDeadlockRepro
{
    class Program
    {
        static ManualResetEvent quitEvent = new ManualResetEvent(false);
        static ManualResetEvent browserSetEvent = new ManualResetEvent(false);

        static async Task Main(string[] args)
        {
            var browserFetcher = new BrowserFetcher();
            Console.WriteLine("fetching browser");
            await browserFetcher.DownloadAsync(BrowserFetcher.DefaultRevision);

            var browser = GetBrowserFromAnotherThread();

            Console.CancelKeyPress += (sender, eArgs) =>
            {
                Console.WriteLine("App killed");
                quitEvent.Set();
                eArgs.Cancel = true;
            };

            RunIndefinitely(browser);

            quitEvent.WaitOne();
            
            // cleanup code here
        }

        private static Browser GetBrowserFromAnotherThread()
        {
            Browser browser = null;
            Console.WriteLine("launching browser");
            var thread = new Thread(async () =>
            {
                browser = await Puppeteer.LaunchAsync
                (
                    new LaunchOptions
                    {
                        Headless = false
                    }
                );
                browserSetEvent.Set();


            });
            
            thread.Start();
            browserSetEvent.WaitOne();

            return browser;
        }

        private static void RunIndefinitely(Browser browser)
        {
            var thread = new Thread(async () =>
            {
                while (true)
                {
                    await PrintPageInfo(browser);
                    Console.WriteLine("loop finished");
                    await Task.Delay(TimeSpan.FromSeconds(5));
                }
            });
            thread.Start();
        }

        private static async Task PrintPageInfo(Browser browser)
        {
            var url = "https://www.google.com";

            Console.WriteLine("opening new page");
            var page = await browser.NewPageAsync();
            Console.WriteLine("starting navigation");
            await page.GoToAsync(url);
            Console.WriteLine("waiting for navigation");
            var contents = await page.GetContentAsync();
            Console.WriteLine($"{url} : {contents.Length}");
        }
    }
}
```

let's hope that this issue thread issue doesn't pop up elsewhere.

**Comment by ReinisV** [comment]
Forgot to update this thread, I solved this issue using the `EnqueueAsyncMessages` option that is available in the current master code of this repo:
``` C#
          await Puppeteer.LaunchAsync
            (
                new LaunchOptions
                {
                    EnqueueAsyncMessages = true
                }
            );
```

Hoping for a release soon, so that I can start using the package version of this.
