### ISSUE TITLE
Flaky Page Close Test

### ISSUE THREAD

**Issue by Androbin** [hardkoded/puppeteer-sharp#1651]
https://ci.appveyor.com/project/kblok/puppeteer-sharp/builds/38258335/job/74y3bkkee23q45ri#L86

```
[xUnit.net 00:01:41.61]     PuppeteerSharp.Tests.PageTests.CloseTests.ShouldSetThePageCloseState [FAIL]
  Failed PuppeteerSharp.Tests.PageTests.CloseTests.ShouldSetThePageCloseState [10 ms]
  Error Message:
   Assert.True() Failure
Expected: True
Actual:   False
  Stack Trace:
     at PuppeteerSharp.Tests.PageTests.CloseTests.<ShouldSetThePageCloseState>d__5.MoveNext() in C:\projects\puppeteer-sharp\lib\PuppeteerSharp.Tests\PageTests\CloseTests.cs:line 95
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

See https://github.com/hardkoded/puppeteer-sharp/pull/1650#issuecomment-800703180

**Comment by kblok** [comment]
Closed due to inactivity. Feel free to reopen it if needed.
