### ISSUE TITLE
PDF: Page.PdfStreamAsync throws MessageException: Protocol error (IO.read): Read failed 

### ISSUE THREAD

**Issue by axunonb** [hardkoded/puppeteer-sharp#1658]
### Complete minimal example reproducing the issue

```csharp
var options = new PuppeteerSharp.LaunchOptions
{
    // --use-cmd-decoder=passthrough causes Chromium error
    Headless = true,
    Args = new[]
        {"--no-sandbox", "--disable-gpu", "--disable-extensions", "--use-cmd-decoder=validating"},
    ExecutablePath = pathToChromium, Timeout = 10000
};
using var browser = await PuppeteerSharp.Puppeteer.LaunchAsync(options).ConfigureAwait(false);
using var page = await browser.NewPageAsync().ConfigureAwait(false);
var html = "<html><body><h1>Test HTML to PDF</h1></body></html>";
await page.SetContentAsync(html);

// Throws PuppeteerSharp.MessageException: Protocol error (IO.read): Read failed
var result = await page.PdfStreamAsync(new PuppeteerSharp.PdfOptions
        {Scale = 1.0M, Format = PaperFormat.A4}).ConfigureAwait(false));
```

### Expected behavior:

PdfStreamAsync returns a stream with the converted PDF document

### Actual behavior:

* Local machine: as expected
* External web server: PuppeteerSharp.MessageException: Protocol error (IO.read): Read failed

### Versions

* PuppeteerSharp 2.0.4
* .NET Core 3.1
* Chromium 83.0.4099.0 (pre-installed)

### Additional Information

This works on the web server:

1. Invoking Chromium without PuppeteerSharp but with PuppeteerSharp's arguments generates a PDF file as expected
```csharp
var tempdir = Path.Combine(Path.GetTempPath(), Path.GetRandomFileName());
Directory.CreateDirectory(tempdir);
var tempFile = Path.Combine(Path.GetTempPath(), Path.GetRandomFileName());

new System.Diagnostics.ProcessStartInfo(pathToChromium,
        $"--disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=TranslateUI --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --headless --hide-scrollbars --mute-audio --no-sandbox --disable-gpu --disable-extensions --use-cmd-decoder=validating --no-margins --user-data-dir={tempdir} --print-to-pdf={tempFile} https://google.com/")
```

2. Screenshot works as expected
```csharp
var result = await page.ScreenshotStreamAsync(new PuppeteerSharp.ScreenshotOptions
                            {FullPage = true, Quality = 100, Type = ScreenshotType.Jpeg}).ConfigureAwait(false);
```

**Logged before calling PdfStreamAsync**:
* Chromium Process: physical memory = 37.773.312 bytes, exited = False, start arguments = --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=TranslateUI --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --headless --hide-scrollbars --mute-audio about:blank --no-sandbox --disable-gpu --disable-extensions --use-cmd-decoder=validating --remote-debugging-port=0 --user-data-dir="D:\Temp\2jw
* Chromium CDP session: Closed = False, Reason = , SessionId = 6C80D4972FE859B5908E25010587C8DE

**Comment by kblok** [comment]
Closed due to inactivity. Feel free to reopen it if needed.

**Comment by axunonb** [comment]
@kblok  Still getting the same behavior with `PuppeteerSharp 9.0.0` on production server. PDF generation works perfectly on the local machine. If fails even with a HTML simplistic string `<html><body>Test</body></html>`
I already had a look at the source code lines mentioned in the stack trace, but I can't figure out any possible reason.
Any hint what should be checked server side?

```
2023-03-26 14:35:55.5662||FATAL|League.Controllers.Match|ReportSheet failed for match ID '3284' PuppeteerSharp.MessageException: Protocol error (IO.read): Read failed
   at PuppeteerSharp.CDPSession.SendAsync(String method, Object args, Boolean waitForCallback) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\CDPSession.cs:line 94
   at PuppeteerSharp.CDPSession.SendAsync[T](String method, Object args) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\CDPSession.cs:line 55
   at PuppeteerSharp.Helpers.ProtocolStreamReader.ReadProtocolStreamByteAsync(CDPSession client, String handle, String path) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\Helpers\ProtocolStreamReader.cs:line 63
   at PuppeteerSharp.Page.PdfInternalAsync(String file, PdfOptions options) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\Page.cs:line 1175
   at League.Caching.ReportSheetCache.GetReportSheetPuppeteer(Int64 matchId, String html, CancellationToken cancellationToken)
   at League.Caching.ReportSheetCache.GetReportSheetPuppeteer(Int64 matchId, String html, CancellationToken cancellationToken)
   at League.Caching.ReportSheetCache.GetReportSheetPuppeteer(Int64 matchId, String html, CancellationToken cancellationToken)
   at League.Caching.ReportSheetCache.GetOrCreatePdf(MatchReportSheetRow data, String html, CancellationToken cancellationToken)
   at League.Controllers.Match.ReportSheet(Int64 id, ReportSheetCache cache, CancellationToken cancellationToken)    at PuppeteerSharp.CDPSession.SendAsync(String method, Object args, Boolean waitForCallback) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\CDPSession.cs:line 94
   at PuppeteerSharp.CDPSession.SendAsync[T](String method, Object args) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\CDPSession.cs:line 55
   at PuppeteerSharp.Helpers.ProtocolStreamReader.ReadProtocolStreamByteAsync(CDPSession client, String handle, String path) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\Helpers\ProtocolStreamReader.cs:line 63
   at PuppeteerSharp.Page.PdfInternalAsync(String file, PdfOptions options) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\Page.cs:line 1175
   at League.Caching.ReportSheetCache.GetReportSheetPuppeteer(Int64 matchId, String html, CancellationToken cancellationToken)
   at League.Caching.ReportSheetCache.GetReportSheetPuppeteer(Int64 matchId, String html, CancellationToken cancellationToken)
   at League.Caching.ReportSheetCache.GetReportSheetPuppeteer(Int64 matchId, String html, CancellationToken cancellationToken)
   at League.Caching.ReportSheetCache.GetOrCreatePdf(MatchReportSheetRow data, String html, CancellationToken cancellationToken)
   at League.Controllers.Match.ReportSheet(Int64 id, ReportSheetCache cache, CancellationToken cancellationToken)
```

**Comment by kblok** [comment]
That code is working for me on v9 @axunonb.
Did you try downloading the browser using `BrowserFetcher` instead of using your own browser?

**Comment by axunonb** [comment]
The code is working for me too, but only on the local machine.
It fails on the production server.
I tried using `BrowserFetcher` instead of the manually installed browser, but the failure is the very same.
This still works fine locally *and* on the production server (variables used as arguments are self-explanatory, I think):
```cs
var startInfo = new System.Diagnostics.ProcessStartInfo(_pathToChromium,
                $"--allow-pre-commit-input --disable-background-networking --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=Translate,BackForwardCache,AcceptCHFrame,MediaRouter,OptimizationHints --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --enable-automation --enable-blink-features=IdleDetection --enable-features=NetworkServiceInProcess2 --export-tagged-pdf --force-color-profile=srgb --metrics-recording-only --no-first-run --password-store=basic --use-mock-keychain --headless --hide-scrollbars --mute-audio --no-sandbox --disable-gpu --use-cmd-decoder=passthrough --no-margins --user-data-dir={tempFolder} --print-to-pdf={pdfFile} {htmlUri}")
            { CreateNoWindow = true, UseShellExecute = false };
var proc = System.Diagnostics.Process.Start(startInfo);
```
