### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by Androbin** [hardkoded/puppeteer-sharp#1670]
```
PuppeteerSharp.NavigationException: Navigation failed because browser has disconnected! (Connection failed to process Runtime.executionContextCreated. Object reference not set to an instance of an object..
    at PuppeteerSharp.DOMWorld.SetContext(ExecutionContext context) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\DOMWorld.cs:line 37
    at PuppeteerSharp.FrameManager.OnExecutionContextCreatedAsync(ContextPayload contextPayload) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\FrameManager.cs:line 291
    at PuppeteerSharp.FrameManager.Client_MessageReceived(Object sender, MessageEventArgs e) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\FrameManager.cs:line 218)
 ---> PuppeteerSharp.TargetClosedException: Navigation failed because browser has disconnected! (Connection failed to process Runtime.executionContextCreated. Object reference not set to an instance of an object..
    at PuppeteerSharp.DOMWorld.SetContext(ExecutionContext context) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\DOMWorld.cs:line 37
    at PuppeteerSharp.FrameManager.OnExecutionContextCreatedAsync(ContextPayload contextPayload) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\FrameManager.cs:line 291
    at PuppeteerSharp.FrameManager.Client_MessageReceived(Object sender, MessageEventArgs e) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\FrameManager.cs:line 218)
   at PuppeteerSharp.Helpers.TaskHelper.WithTimeout(Task task, Func`1 timeoutAction, TimeSpan timeout, CancellationToken cancellationToken) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\Helpers\TaskHelper.cs:line 82
   at PuppeteerSharp.FrameManager.NavigateFrameAsync(Frame frame, String url, NavigationOptions options) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\FrameManager.cs:line 130
   --- End of inner exception stack trace ---
```

```
PuppeteerSharp.NavigationException: Protocol error (Page.navigate): Session closed. Most likely the Page has been closed.Close reason: Connection failed to process Runtime.executionContextCreated. Object reference not set to an instance of an object..
    at PuppeteerSharp.DOMWorld.SetContext(ExecutionContext context) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\DOMWorld.cs:line 37
    at PuppeteerSharp.FrameManager.OnExecutionContextCreatedAsync(ContextPayload contextPayload) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\FrameManager.cs:line 291
    at PuppeteerSharp.FrameManager.Client_MessageReceived(Object sender, MessageEventArgs e) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\FrameManager.cs:line 218
 ---> PuppeteerSharp.PuppeteerException: Protocol error (Page.navigate): Session closed. Most likely the Page has been closed.Close reason: Connection failed to process Runtime.executionContextCreated. Object reference not set to an instance of an object..
    at PuppeteerSharp.DOMWorld.SetContext(ExecutionContext context) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\DOMWorld.cs:line 37
    at PuppeteerSharp.FrameManager.OnExecutionContextCreatedAsync(ContextPayload contextPayload) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\FrameManager.cs:line 291
    at PuppeteerSharp.FrameManager.Client_MessageReceived(Object sender, MessageEventArgs e) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\FrameManager.cs:line 218
   at PuppeteerSharp.CDPSession.SendAsync(String method, Object args, Boolean waitForCallback) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\CDPSession.cs:line 157
   at PuppeteerSharp.CDPSession.SendAsync[T](String method, Object args) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\CDPSession.cs:line 109
   at PuppeteerSharp.FrameManager.NavigateAsync(CDPSession client, String url, String referrer, String frameId) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\FrameManager.cs:line 147
   at PuppeteerSharp.FrameManager.NavigateFrameAsync(Frame frame, String url, NavigationOptions options) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\FrameManager.cs:line 130
   --- End of inner exception stack trace ---
```

https://github.com/hardkoded/puppeteer-sharp/blob/8262c805fc32a63cb3390d71a26260c2c5224013/lib/PuppeteerSharp/DOMWorld.cs#L39

https://github.com/puppeteer/puppeteer/blob/b349c91e7df76630b7411d6645e649945c4609bd/src/common/DOMWorld.ts#L119

See upstream issue https://github.com/puppeteer/puppeteer/issues/4197

**Comment by Androbin** [comment]
@kblok What could possibly have a `null` value here?

**Comment by kblok** [comment]
@Androbin It could be the `_contextResolveTaskWrapper` due to a race condition.
We could create a context if `_contextResolveTaskWrapper` is null. I would also add a `lock (_contextResolveTaskWrapper)` to prevent some other racing conditions.

**Comment by Androbin** [comment]
@kblok Please explain how that race condition would work.
As far as I understand, `_contextResolveTaskWrapper` gets implicitly initialized with `null`, then immediately gets assigned an instance value in the constructor call to `SetContext`, then never set to `null` again.
I would like to think it's not possible for the `DOMWorld` instance to be used and the `SetContext` method called with an instance value before the constructor has called `SetContext` with `null` and finished executing.

**Comment by kblok** [comment]
As messages might be processed in parallel. The `Runtime.executionContextCreated` can start being processed while the `DOMWorld` instance is still in progress.

We don't have that issue in Javascript because the even loop in Node.JS process messages in serial.

**Comment by Androbin** [comment]
That would require a reference to a partially-constructed `DOMWorld` object:
http://joeduffyblog.com/2010/06/27/on-partiallyconstructed-objects/

For example, the `Frame` constructor is leaking `this`: #1677

The `DOMWorld` constructor does not leak `this`, so I don't understand how there can be a problem.

https://github.com/hardkoded/puppeteer-sharp/blob/82a48af5d9a02e2a7ebfb8b973b20f555bf5342e/lib/PuppeteerSharp/Frame.cs#L72
https://github.com/hardkoded/puppeteer-sharp/blob/647201566bab32d257f6b3969bf272b25b90b3bf/lib/PuppeteerSharp/FrameManager.cs#L274

`frame.MainWorld` and `frame.SecondaryWorld` are both `null` until the `DOMWorld` constructor has finished executing and the reference is assigned to the field afterwards.

**Comment by Androbin** [comment]
> It could be the `_contextResolveTaskWrapper` due to a race condition.

@kblok I would really like to understand this. Could you maybe step me through what two different threads might be doing to produce this race condition?

**Comment by kblok** [comment]
>@kblok I would really like to understand this. Could you maybe step me through what two different threads might be doing to produce this race condition?

Sure, again, this could be crazy stuff. Let's say that one thread creates the frame and between the Frame is assigned https://github.com/hardkoded/puppeteer-sharp/blob/82a48af5d9a02e2a7ebfb8b973b20f555bf5342e/lib/PuppeteerSharp/DOMWorld.cs#L26 and the context is set https://github.com/hardkoded/puppeteer-sharp/blob/8262c805fc32a63cb3390d71a26260c2c5224013/lib/PuppeteerSharp/DOMWorld.cs#L29

Another thread process the message `Runtime.executionContextCreated` https://github.com/hardkoded/puppeteer-sharp/blob/82a48af5d9a02e2a7ebfb8b973b20f555bf5342e/lib/PuppeteerSharp/FrameManager.cs#L196
In that scenario, the TaskCompletionSource would still be null...

**Comment by Androbin** [comment]
@kblok Please demonstrate how the reference to the `DOMWorld` object ends up in `OnExecutionContextCreatedAsync`.

**Comment by kblok** [comment]
@Androbin  I have no idea, just a theory.

**Comment by Androbin** [comment]
The code should essentially be equivalent to this:

```
var frameTaskWrapper = new TaskCompletionSource<Frame>();
```

Thread 1:
```
var frame = new Frame(...);
var world = new DOMWorld(...);
world._contextResolveTaskWrapper = new TaskCompletionSource<ExecutionContext>();
frame.MainWorld = world;
frameTaskWrapper.SetResult(frame);
```

Thread 2:

```
var frame = await frameTaskWrapper.Task;
DOMWorld world = frame.MainWorld;
var context = new ExecutionContext(...);
world.SetContext(context);
```

**Comment by Androbin** [comment]
Please note:
- The `DOMWorld` constructor finishes executing before `frame.MainWorld` is assigned.
- The `Frame` constructor finishes executing before `SetResult` is called.

**Comment by Androbin** [comment]
Potential candidates for `null` value in `SetContext`:
- `_contextResolveTaskWrapper`
- - initialized in constructor
- - never assigned a `null` value
- `WaitTasks`
- - initialized in constructor
- - never re-assigned
- `waitTask`
- - `WaitTasks.Add` never called with potentially `null` value.

**Comment by Androbin** [comment]
@kblok Must-read:
https://stackoverflow.com/questions/29146200/why-is-or-isnt-setting-fields-in-a-constructor-thread-safe

**Comment by Androbin** [comment]
I talked to a friend about this and he thinks this is about instruction reordering and missing synchronisation when passing newly constructed objects to other threads. For the most part, the `ConcurrentDictionary` used to pass `Frame` objects from one thread to another are making things work.
But we have some weak spots like the unsynchronized list from #1677 and others, see #1680.

**Comment by kblok** [comment]
Closed due to inactivity. Feel free to reopen it if needed.
