### ISSUE TITLE
Space getting slowly eaten away by chrome

### ISSUE THREAD

**Issue by mrtristan** [hardkoded/puppeteer-sharp#1713]
Been running a process on Docker (hosted in AWS so i don't have access to any raw data) every X period. Just heard that some things aren't behaving so looked in to it and the issue was that space was slowly disappearing. I'm assuming that it's due to browser folders building up. Is there a way to clean up after a browser once it's gone?

if it's helpful at all, i'm launching with the following args:
```
"--no-sandbox",
"--disable-gpu",
"--no-zygote",
"--disable-setuid-sandbox",
"--disable-dev-shm-usage",
"--disable-accelerated-2d-canvas",
"--no-first-run",
```

the error:
```
System.IO.IOException: No space left on device
   at System.IO.FileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at PuppeteerSharp.Helpers.TempDirectory..ctor(String path) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\Helpers\TempDirectory.cs:line 25
   at PuppeteerSharp.ChromiumLauncher.PrepareChromiumArgs(LaunchOptions options) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\ChromiumLauncher.cs:line 77
   at PuppeteerSharp.ChromiumLauncher..ctor(String executable, LaunchOptions options) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\ChromiumLauncher.cs:line 62
   at PuppeteerSharp.Launcher.LaunchAsync(LaunchOptions options) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\Launcher.cs:line 88```

**Comment by kblok** [comment]
I have no idea how to improve this. PRs are welcome.
