### ISSUE TITLE
PuppeteerSharp.TargetClosedException thrown at PuppeteerSharp.Page.OnTargetCrashed()

### ISSUE THREAD

**Issue by HunteRoi** [hardkoded/puppeteer-sharp#1801]
### Description

I have a web API built on a clean architecture with CQRS that uses https://github.com/PejmanNik/puppeteer-report-csharp to generate a PDF file from an HTML string.

It seems that a `PuppeteerSharp.TargetClosedException` is thrown here : `at PuppeteerSharp.Page.OnTargetCrashed() in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\Page.cs:line 2296`.

This might be related to https://github.com/hardkoded/puppeteer-sharp/issues/1016.

### Complete minimal example reproducing the issue
*I haven't tested the following implementation outside of my application.*

```csharp
// IPuppeeterReportGenerator.cs
public interface IPuppeteerReportGenerator : IPuppeteerReport
{
    Task<byte[]> GeneratePDFFromHtml(string htmlContent, PdfOptions options);
}

// PuppeeterReportGenerator.cs
public class PuppeeterReportGenerator : PuppeteerReport, IPuppeteerReportGenerator
{
    public async Task<byte[]> GeneratePDFFromHtml(string htmlContent, PdfOptions options)
    {
        await new BrowserFetcher().DownloadAsync(BrowserFetcher.DefaultChromiumRevision);
        var browser = await Puppeteer.LaunchAsync(new LaunchOptions
        {
            Headless = true,
            Args = new[]
            {
                    "--no-sandbox",
                    "--disable-setuid-sandbox",
                    "--disable-dev-shm-usage"
            }
        });

        var page = await browser.NewPageAsync();
        await page.SetContentAsync(htmlContent);

        var result = await PDFPage(page, options);
        
        await page.CloseAsync(); // error thrown before hitting here
        await browser.CloseAsync();

        return result;
    }
}
```

### Expected behavior:

The page is loaded based on the HTML input provided, then the PDF file is generated. The page is then closed, the browser too and everything goes smoothly.

### Actual behavior:

A `TargetClosedException` is thrown before arriving to `await page.CloseAsync();`.

### Versions
* I am using https://github.com/PejmanNik/puppeteer-report-csharp version 3.0.2
* The above package uses PuppeteerSharp version 4.0.0
* My .NET environment is .NET 5.0

### Additional Information

My application applies the CQRS pattern in a Clean Architecture. Everything related to the generation of the PDF is in the Infrastructure project of the solution.

**Comment by HunteRoi** [comment]
Here is the stacktrace/output when running the app and hitting the exception: [output.txt](https://github.com/hardkoded/puppeteer-sharp/files/7135255/output.txt).

```
Application.V1.Candidates.Queries.GenerateCandidateCvQuery.GenerateCandidateCvQuery: Error: Request: Unhandled Exception for Request GenerateCandidateCvQuery Application.V1.Candidates.Queries.GenerateCandidateCvQuery.GenerateCandidateCvQuery

PuppeteerSharp.TargetClosedException: Protocol error(Runtime.callFunctionOn): Target closed. (Page failed to process Inspector.targetCrashed. Exception of type 'PuppeteerSharp.TargetCrashedException' was thrown..    at PuppeteerSharp.Page.OnTargetCrashed() in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\Page.cs:line 2296
   at PuppeteerSharp.Page.Client_MessageReceived(Object sender, MessageEventArgs e) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\Page.cs:line 2103)
   at PuppeteerSharp.CDPSession.SendAsync(String method, Object args, Boolean waitForCallback) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\CDPSession.cs:line 156
   at PuppeteerSharp.CDPSession.SendAsync[T](String method, Object args) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\CDPSession.cs:line 107
   at PuppeteerSharp.ExecutionContext.ExecuteEvaluationAsync(String method, Object args) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\ExecutionContext.cs:line 163
   at PuppeteerSharp.ExecutionContext.EvaluateFunctionHandleAsync(String script, Object[] args) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\ExecutionContext.cs:line 105
   at PuppeteerSharp.DOMWorld.<AddScriptTagAsync>g__AddScriptTagPrivate|29_0(String script, String urlOrContent, String type) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\DOMWorld.cs:line 192
   at PuppeteerSharp.DOMWorld.AddScriptTagAsync(AddTagOptions options) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\DOMWorld.cs:line 219
   at PuppeteerReportCsharp.PuppeteerReport.PDFPage(Page page, PdfOptions options)
   at Infrastructure.V1.Services.CvGenerators.PuppeeterReportGenerator.GeneratePDFFromHtml(String htmlContent, PdfOptions options) in C:\GIT\automated-cv-generation\src\Infrastructure\V1\Services\CvGenerators\PuppeteerReportGenerator.cs:line 32
   at Infrastructure.V1.Services.CvGenerators.BNP.BNPCvGenerator.GenerateAsync(CvGenerationModel model) in C:\GIT\automated-cv-generation\src\Infrastructure\V1\Services\CvGenerators\BNP\BNPCvGenerator.cs:line 49
   at Application.V1.Candidates.Handlers.CandidatesQueriesHandler.Handle(GenerateCandidateCvQuery request, CancellationToken cancellationToken) in C:\GIT\automated-cv-generation\src\Application\V1\Candidates\Handlers\CandidatesQueriesHandler.cs:line 91
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at Application.V1.Common.Behaviours.ValidationBehaviour`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next) in C:\GIT\automated-cv-generation\src\Application\V1\Common\Behaviours\ValidationBehaviour.cs:line 57
   at Application.V1.Common.Behaviours.PerformanceBehaviour`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next) in C:\GIT\automated-cv-generation\src\Application\V1\Common\Behaviours\PerformanceBehaviour.cs:line 65
   at Application.V1.Common.Behaviours.UnhandledExceptionBehaviour`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next) in C:\GIT\automated-cv-generation\src\Application\V1\Common\Behaviours\UnhandledExceptionBehaviour.cs:line 47
Exception thrown: 'PuppeteerSharp.TargetClosedException' in Application.dll
Exception thrown: 'PuppeteerSharp.TargetClosedException' in System.Private.CoreLib.dll
Presentation.Filters.V1.ApiExceptionFilterAttribute: Error: An error occured while processing a request. See stacktrace below:

PuppeteerSharp.TargetClosedException: Protocol error(Runtime.callFunctionOn): Target closed. (Page failed to process Inspector.targetCrashed. Exception of type 'PuppeteerSharp.TargetCrashedException' was thrown..    at PuppeteerSharp.Page.OnTargetCrashed() in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\Page.cs:line 2296
   at PuppeteerSharp.Page.Client_MessageReceived(Object sender, MessageEventArgs e) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\Page.cs:line 2103)
   at PuppeteerSharp.CDPSession.SendAsync(String method, Object args, Boolean waitForCallback) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\CDPSession.cs:line 156
   at PuppeteerSharp.CDPSession.SendAsync[T](String method, Object args) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\CDPSession.cs:line 107
   at PuppeteerSharp.ExecutionContext.ExecuteEvaluationAsync(String method, Object args) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\ExecutionContext.cs:line 163
   at PuppeteerSharp.ExecutionContext.EvaluateFunctionHandleAsync(String script, Object[] args) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\ExecutionContext.cs:line 105
   at PuppeteerSharp.DOMWorld.<AddScriptTagAsync>g__AddScriptTagPrivate|29_0(String script, String urlOrContent, String type) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\DOMWorld.cs:line 192
   at PuppeteerSharp.DOMWorld.AddScriptTagAsync(AddTagOptions options) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\DOMWorld.cs:line 219
   at PuppeteerReportCsharp.PuppeteerReport.PDFPage(Page page, PdfOptions options)
   at Infrastructure.V1.Services.CvGenerators.PuppeeterReportGenerator.GeneratePDFFromHtml(String htmlContent, PdfOptions options) in C:\GIT\automated-cv-generation\src\Infrastructure\V1\Services\CvGenerators\PuppeteerReportGenerator.cs:line 32
   at Infrastructure.V1.Services.CvGenerators.BNP.BNPCvGenerator.GenerateAsync(CvGenerationModel model) in C:\GIT\automated-cv-generation\src\Infrastructure\V1\Services\CvGenerators\BNP\BNPCvGenerator.cs:line 49
   at Application.V1.Candidates.Handlers.CandidatesQueriesHandler.Handle(GenerateCandidateCvQuery request, CancellationToken cancellationToken) in C:\GIT\automated-cv-generation\src\Application\V1\Candidates\Handlers\CandidatesQueriesHandler.cs:line 91
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at Application.V1.Common.Behaviours.ValidationBehaviour`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next) in C:\GIT\automated-cv-generation\src\Application\V1\Common\Behaviours\ValidationBehaviour.cs:line 57
   at Application.V1.Common.Behaviours.PerformanceBehaviour`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next) in C:\GIT\automated-cv-generation\src\Application\V1\Common\Behaviours\PerformanceBehaviour.cs:line 65
   at Application.V1.Common.Behaviours.UnhandledExceptionBehaviour`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next) in C:\GIT\automated-cv-generation\src\Application\V1\Common\Behaviours\UnhandledExceptionBehaviour.cs:line 47
   at Presentation.Controllers.V1.CandidatesController.GenerateCandidateCvAsync(String email, String profile, String template) in C:\GIT\automated-cv-generation\src\Presentation\Controllers\V1\CandidatesController.cs:line 54
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor: Information: Executing ObjectResult, writing value of type 'Microsoft.AspNetCore.Mvc.ProblemDetails'.
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker: Information: Executed action Presentation.Controllers.V1.CandidatesController.GenerateCandidateCvAsync (Presentation) in 86969.5311ms
Microsoft.AspNetCore.Routing.EndpointMiddleware: Information: Executed endpoint 'Presentation.Controllers.V1.CandidatesController.GenerateCandidateCvAsync (Presentation)'
Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request finished HTTP/2 GET https://localhost:5001/api/v1/candidates/dummy.candidate@capyx.be/cv?profile=Developer&template=BNP - - - 500 149 application/problem+json;+charset=utf-8 87050.4851ms
The thread 0x393c has exited with code 0 (0x0).
The thread 0x2fa8 has exited with code 0 (0x0).
The thread 0x4d6c has exited with code 0 (0x0).
The thread 0xf48 has exited with code 0 (0x0).

```

**Comment by kblok** [comment]
Target closed would tell you that the target crashed. There isn't much pptr# can do about that.
