### ISSUE TITLE
Exception using Firefox

### ISSUE THREAD

**Issue by trebor678** [hardkoded/puppeteer-sharp#1808]
I'm trying to connect Pupperteer to Firefox. The page loads up but whenever I try to access something like GetContentAsync I get the following exception.

```
Protocol error (Runtime.callFunctionOn): Session closed. Most likely the Page has been closed.Close reason: Page failed to process Runtime.consoleAPICalled. Error converting value "timeStamp" to type 'PuppeteerSharp.ConsoleType'. Path 'type'..    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject[T](JsonSerializer jsonSerializer)
   at PuppeteerSharp.Page.Client_MessageReceived(Object sender, MessageEventArgs e) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\Page.cs:line 2131
```

I'm letting Pupperteer download it's own version of Firefox which is '94.0a1'. I can't seem to find a way to change which version it uses though, in case it's the latest nightly build that's causing the issue

**Comment by kblok** [comment]
Thanks for the report @trebor678 !
We should fix this.

**Comment by trebor678** [comment]
@kblok That exception has now been fixed but unfortunately I'm getting a new exception when calling the 'GetContentAsync' method

```
PuppeteerSharp.TargetClosedException: Protocol error(Runtime.callFunctionOn): Target closed. (Page failed to process Runtime.consoleAPICalled. Error reading string. Unexpected token: StartObject. Path ''..    at Newtonsoft.Json.JsonReader.ReadAsString()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject[T](JsonSerializer jsonSerializer)
   at PuppeteerSharp.Helpers.Json.JTokenExtensions.ToObject[T](JToken token, JsonSerializerSettings jsonSerializerSettings) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\Helpers\Json\JTokenExtensions.cs:line 41
   at PuppeteerSharp.Helpers.Json.JTokenExtensions.ToObject[T](JToken token, Boolean camelCase) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\Helpers\Json\JTokenExtensions.cs:line 23
   at PuppeteerSharp.Helpers.RemoteObjectHelper.ValueFromType[T](JToken value, RemoteObjectType objectType, Boolean stringify) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\Helpers\RemoteObjectHelper.cs:line 70
   at PuppeteerSharp.Helpers.RemoteObjectHelper.ValueFromRemoteObject[T](RemoteObject remoteObject, Boolean stringify) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\Helpers\RemoteObjectHelper.cs:line 42
   at PuppeteerSharp.Page.<>c.<AddConsoleMessageAsync>b__248_1(JSHandle i) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\Page.cs:line 2375
   at System.Linq.Enumerable.SelectArrayIterator`2.MoveNext()
   at System.String.JoinCore[T](Char* separator, Int32 separatorLength, IEnumerable`1 values)
   at System.String.Join[T](String separator, IEnumerable`1 values)
   at PuppeteerSharp.Page.AddConsoleMessageAsync(ConsoleType type, JSHandle[] values, StackTrace stackTrace) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\Page.cs:line 2388
   at PuppeteerSharp.Page.Client_MessageReceived(Object sender, MessageEventArgs e) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\Page.cs:line 2116)
   at PuppeteerSharp.CDPSession.SendAsync(String method, Object args, Boolean waitForCallback) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\CDPSession.cs:line 165
   at PuppeteerSharp.CDPSession.SendAsync[T](String method, Object args) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\CDPSession.cs:line 116
   at PuppeteerSharp.ExecutionContext.ExecuteEvaluationAsync(String method, Object args) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\ExecutionContext.cs:line 163
   at PuppeteerSharp.ExecutionContext.RemoteObjectTaskToObject[T](Task`1 remote) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\ExecutionContext.cs:line 134
   at PuppeteerSharp.DOMWorld.EvaluateFunctionAsync[T](String script, Object[] args) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\DOMWorld.cs:line 100
```

It seems to happen whenever calling anything on the page once it's loaded.
