### ISSUE TITLE
PuppeteerSharp.TargetClosedException

### ISSUE THREAD

**Issue by Chr0nicT** [hardkoded/puppeteer-sharp#1820]
Hey!
I’m having an issue on this (linked with PuppeteerExtra)

"Unhandled Exception PuppererSharp.TargetClosedException: Protocol error(Page.addScriptToEvaluateOnNewDocument): Target closed. (Target.detachedFromTarget)”
The first line it shows is CDPSession.cs (line 157)

some ways down it also says: “PuppeteerExtraSharp.Plugins.ExtraStealth.Evasions.UserAgent.OnPageCreated”

if it helps any I’m using this with Parrellization as well.

help would be much appreciated!
Thank you!

**Comment by RevSearches** [comment]
I to am having this issue:
```PuppeteerSharp.TargetClosedException
  HResult=0x80131500
  Message=Protocol error(Page.addScriptToEvaluateOnNewDocument): Target closed. (Target.detachedFromTarget)
  Source=System.Private.CoreLib
  StackTrace:
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PuppeteerSharp.CDPSession.<SendAsync>d__33.MoveNext() in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\CDPSession.cs:line 165
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PuppeteerExtraSharp.Plugins.ExtraStealth.Evasions.OutDimensions.<OnPageCreated>d__1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PuppeteerExtraSharp.PuppeteerExtra.<>c__DisplayClass9_1.<<Register>b__2>d.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

  This exception was originally thrown at this call stack:
    [External Code]```
