### ISSUE TITLE
Exception is thrown when calling GetContentAsync()

### ISSUE THREAD

**Issue by toebeans** [hardkoded/puppeteer-sharp#1858]
### Description

Exception is thrown when calling GetContentAsync()

### Complete minimal example reproducing the issue

```csharp
        [TestMethod]
        public async Task DownloadStringTest()
        {
            var browser = await Puppeteer.LaunchAsync(new LaunchOptions
            {
                Headless = true,
                Product = Product.Firefox
            });

            var page = await browser.NewPageAsync();
            await page.GoToAsync("https://www.otcmarkets.com/stock/WRIT/security");

            var content = await page.GetContentAsync();

            Assert.IsFalse(string.IsNullOrWhiteSpace(content));
        }
```

### Expected behavior:

Expect html content to be available

### Actual behavior:

Exception is thrown (see below)

### Versions

Puppeteer v5.1

### Additional Information

Test method DownloadStringTest threw exception: 
    PuppeteerSharp.TargetClosedException: Protocol error(Runtime.callFunctionOn): Target closed. (Page failed to process Runtime.consoleAPICalled. Error reading string. Unexpected token: StartArray. Path ''..    at Newtonsoft.Json.JsonReader.ReadAsString()
       at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
       at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
       at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
       at Newtonsoft.Json.Linq.JToken.ToObject[T](JsonSerializer jsonSerializer)
       at PuppeteerSharp.Helpers.Json.JTokenExtensions.ToObject[T](JToken token, JsonSerializerSettings jsonSerializerSettings) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\Helpers\Json\JTokenExtensions.cs:line 41
       at PuppeteerSharp.Helpers.Json.JTokenExtensions.ToObject[T](JToken token, Boolean camelCase) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\Helpers\Json\JTokenExtensions.cs:line 23
       at PuppeteerSharp.Helpers.RemoteObjectHelper.ValueFromType[T](JToken value, RemoteObjectType objectType, Boolean stringify) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\Helpers\RemoteObjectHelper.cs:line 70
       at PuppeteerSharp.Helpers.RemoteObjectHelper.ValueFromRemoteObject[T](RemoteObject remoteObject, Boolean stringify) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\Helpers\RemoteObjectHelper.cs:line 42
       at PuppeteerSharp.Page.<>c.<AddConsoleMessageAsync>b__248_1(JSHandle i) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\Page.cs:line 2375
       at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
       at System.String.Join[T](String separator, IEnumerable`1 values)
       at PuppeteerSharp.Page.<AddConsoleMessageAsync>d__248.MoveNext() in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\Page.cs:line 2388
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at PuppeteerSharp.Page.<Client_MessageReceived>d__235.MoveNext() in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\Page.cs:line 2116)

  Stack Trace: 
    TaskAwaiter.ThrowForNonSuccess(Task task)
    TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    <SendAsync>d__33.MoveNext() line 165
    --- End of stack trace from previous location where exception was thrown ---
    TaskAwaiter.ThrowForNonSuccess(Task task)
    TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    <SendAsync>d__32`1.MoveNext() line 116
    --- End of stack trace from previous location where exception was thrown ---
    TaskAwaiter.ThrowForNonSuccess(Task task)
    TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    <13 more frames...>
    <DownloadUsingBrowserAutomation>d__4.MoveNext() line 55
    --- End of stack trace from previous location where exception was thrown ---
    TaskAwaiter.ThrowForNonSuccess(Task task)
    TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    TaskAwaiter`1.GetResult()
    <DownloadStringTest>d__0.MoveNext() line 17
    --- End of stack trace from previous location where exception was thrown ---
    TaskAwaiter.ThrowForNonSuccess(Task task)
    TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    ThreadOperations.ExecuteWithAbortSafety(Action action)

**Comment by kblok** [comment]
Triage Info: The RemoteObject.Value from a console log is coming as a `JArray` instead of a `JToken`,  breaking the parsing.

**Comment by kblok** [comment]
Closed due to inactivity. Feel free to reopen it if needed.
