### ISSUE TITLE
Error creating incognito browsers in quick succession

### ISSUE THREAD

**Issue by thomaschanneladvisor** [hardkoded/puppeteer-sharp#1898]
### Description
Appears to be a thread issue when creating Incognito browsers really fast. The below message and stack trace explain it.

### Complete minimal example reproducing the issue
I am having trouble reliable recreating it but it would be something like.
-Get browser.
-Multiple threads at the same time use that browser to create an incognito browser.

Exception message:
Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
StackTrace
--
at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at PuppeteerSharp.Browser.CreateIncognitoBrowserContextAsync() in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\Browser.cs:line 217
```
### Expected behavior:
Not throw an error when Incognito browsers are created by different threads at the same time/almost the same time.

### Actual behavior:
Error thrown.

### Versions
 6.1.0

### Additional Information
 It seems the fix would be to use ConcurrentDictionary instead of Dictionary for _contexts. Do you forsee any issue with that change ?

**Comment by kblok** [comment]
I think that makes sense. How do you feel about creating a PR?

**Comment by thomaschanneladvisor** [comment]
I will take a look at doing that.

**Comment by thomaschanneladvisor** [comment]
Added PR here https://github.com/hardkoded/puppeteer-sharp/pull/1899
