### ISSUE TITLE
Get navigation failed error when use GoToAsync

### ISSUE THREAD

**Issue by magdev2022** [hardkoded/puppeteer-sharp#2032]
Hi.
I used code as follow.
```
  var loginBrowser = Puppeteer.LaunchAsync(new LaunchOptions
            {   Headless = false,
                ExecutablePath = chromepath}).Result;
var loginPage = loginBrowser.NewPageAsync().Result;
loginPage.GoToAsync("https://bape.com/account/login").Result;
```

when go to login page, error is occured.
`NavigationException: Navigation failed because browser has disconnected! (Connection failed to process Target.attachedToTarget. Protocol error(Page.setLifecycleEventsEnabled): Target closed. (Target.detachedFromTarget).    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PuppeteerSharp.CDPSession.<SendAsync>d__33.MoveNext() in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\CDPSession.cs:line 97
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PuppeteerSharp.FrameManager.<InitializeAsync>d__44.MoveNext() in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\FrameManager.cs:line 83
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PuppeteerSharp.FrameManager.<OnAttachedToTargetAsync>d__51.MoveNext() in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\FrameManager.cs:line 258
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PuppeteerSharp.FrameManager.<>c__DisplayClass49_0.<<Client_MessageReceived>b__0>d.MoveNext() in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\FrameManager.cs:line 216)
`
How to solve this error? which options are required more?
Regards.

**Comment by shockk73** [comment]
@magdev2022 Hi there, any updates on this issue?
