### ISSUE TITLE
Could not load file or assembly

### ISSUE THREAD

**Issue by hanogin** [hardkoded/puppeteer-sharp#2068]
### Description
i have a web api project traget dot net framowrok 7.2 try to access project target .net standart 2.0 with static class that convert html to pdf using puppeteer
while access to that statuc class i get this error:

```
System.IO.FileNotFoundException
  HResult=0x80070002
  Message=Could not load file or assembly 'PuppeteerSharp, Version=9.0.0.0, Culture=neutral, PublicKeyToken=db12f80f85d8ba23' or one of its dependencies. The system cannot find the file specified.
  Source=ReportToPDF
  StackTrace:
   at ReportToPDF.ReportToPDF.ToPDF() in C:\**\**\ReportToPDF\ReportToPDF.cs:line 60
   at GMN.Api.Controllers.CommonController.ProcessCall(Object data) in C:\c_project**\**.Api\Controllers\CommonController.cs:line 34
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
```

### Versions

* Which version of PuppeteerSharp are you using? 9
* Which .NET runtime and version are you targeting? .net standart 2.0 

Do i need to add some configuration in web.config or csproj of the api project?

**Comment by kblok** [comment]
This is quite a generic error. Did you go through posts like [this one](https://stackoverflow.com/questions/43995432/could-not-load-file-or-assembly-microsoft-extensions-dependencyinjection-abstrac)?
