### ISSUE TITLE
codebase is not supported on assemblies loaded from a single-file bundle

### ISSUE THREAD

**Issue by ispysoftware** [hardkoded/puppeteer-sharp#2124]
### Description

Running on ubuntu linux 20.04 from a published executable using .net 6 I get the error

CodeBase is not supported on assemblies loaded from a single-file bundle.
 at System.Reflection.RuntimeAssembly.get_CodeBase()
 at PuppeteerSharp.BrowserFetcher.GetExecutablePath() in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\BrowserFetcher.cs:line 356
  at PuppeteerSharp.BrowserFetcher..ctor() in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\BrowserFetcher.cs:line 53

### Expected behavior:

Loads and does it's thing

### Actual behavior:

crashes

### Versions

9.0.2

.Net 6.0 app published as a single file

**Comment by jnyrup** [comment]
This sounds like #2088 which hasn't been released yet.

**Comment by kblok** [comment]
v9.1 was released. Enjoy!
