### ISSUE TITLE
MacOs System.ComponentModel.Win32Exception : An error occurred trying to start process 

### ISSUE THREAD

**Issue by stesee** [hardkoded/puppeteer-sharp#2294]
### Description

PuppeteerSharp 11.0.2 is broken on MacOs latest github acitons runners.

### Complete minimal example reproducing the issue

E.g.

```csharp
                using var browserFetcher1 = new BrowserFetcher();
                await browserFetcher1.DownloadAsync();
                await using var browser = await Puppeteer.LaunchAsync(
                    new LaunchOptions { Headless = true });
```

### Expected behavior:

Should not throw an exception

### Actual behavior:

Throws:
```
Error Message:
   System.ComponentModel.Win32Exception : An error occurred trying to start process '/Users/runner/work/PuppeteerSharp.Renderer/PuppeteerSharp.Renderer/Codeuctivity.HtmlRendererTests/bin/Release/net6.0/Chrome/MacOS-115.0.[579](https://github.com/Codeuctivity/PuppeteerSharp.Renderer/actions/runs/6017507623/job/16323842652#step:10:580)0.102/chrome-mac-x64/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing' with working directory '/Users/runner/work/PuppeteerSharp.Renderer/PuppeteerSharp.Renderer/Codeuctivity.HtmlRendererTests/bin/Release/net6.0'. No such file or directory
  Stack Trace:
     at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at PuppeteerSharp.States.ChromiumStartingState.StartCoreAsync(LauncherBase p) in /home/runner/work/puppeteer-sharp/puppeteer-sharp/lib/PuppeteerSharp/States/ChromiumStartingState.cs:line 68
   at PuppeteerSharp.Launcher.LaunchAsync(LaunchOptions options) in /home/runner/work/puppeteer-sharp/puppeteer-sharp/lib/PuppeteerSharp/Launcher.cs:line 66
   at PuppeteerSharp.Launcher.LaunchAsync(LaunchOptions options) in /home/runner/work/puppeteer-sharp/puppeteer-sharp/lib/PuppeteerSharp/Launcher.cs:line 99
   at Codeuctivity.HtmlRenderer.Renderer.InitializeAsync(BrowserFetcher browserFetcher) in /_/Codeuctivity.HtmlRenderer/Renderer.cs:line 103
   at Codeuctivity.HtmlRendererTests.RendererTests.ShouldConvertHtmlToPngNoSandbox(String testFileName) in /Users/runner/work/PuppeteerSharp.Renderer/PuppeteerSharp.Renderer/Codeuctivity.HtmlRendererTests/RendererTests.cs:line 227
--- End of stack trace from previous location ---
```

### Versions

* Version of PuppeteerSharp: 11.0.2
* Reproduced using .net 6 and 7

### Additional Information

Project/Branch where the issue was discovered: https://github.com/Codeuctivity/PuppeteerSharp.Renderer/tree/PuppeteerSharpBreakingChangesV11.0.0

**Comment by stesee** [comment]
I am curious... is there any reason not to test MacOs in https://github.com/hardkoded/puppeteer-sharp/blob/master/.github/workflows/dotnet.yml ?

**Comment by kblok** [comment]
@stesee I just moved everything to GH Actions. I think we can do that :)

**Comment by kblok** [comment]
Could you try 11.0.3?
