### ISSUE TITLE
BrowserFetcher.DownloadAsync throws TaskCanceledException

### ISSUE THREAD

**Issue by mmalvik** [hardkoded/puppeteer-sharp#2306]
### Description
When trying some simple code to download a browser it fails.

Am I using the API wrong? 🤔 

### Complete minimal example reproducing the issue

```csharp
internal class Program
{
    async static Task Main(string[] args)
    {
        await DownloadBrowser().ConfigureAwait(false);
    }

    private static async Task DownloadBrowser()
    {
        BrowserFetcher? browserFetcher;

        browserFetcher = new BrowserFetcher(new BrowserFetcherOptions
        {
            Path = Path.GetTempPath(),
            Browser = SupportedBrowser.Chromium
        });
        try
        {
            await browserFetcher.DownloadAsync(BrowserTag.Latest).ConfigureAwait(false);
        }
        catch (Exception exception)
        {
            Console.WriteLine($"Browser download failed: {exception.Message}");
            throw;
        }

        browserFetcher.Dispose();

        Console.WriteLine("Browser download was successful");
    }
}
```

I have also put a repro here in my fork:
https://github.com/mmalvik/puppeteer-sharp/blob/download-issue/lib/DownloadIssue/Program.cs

### Expected behavior:

My code should print: `Browser download was successful`

### Actual behavior:
Exception is thrown:
```
Unhandled exception. System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at PuppeteerSharp.BrowserFetcher.DownloadAsync(BrowserTag tag) in /Users/mm/WSpace/puppeteer-sharp/lib/PuppeteerSharp/BrowserFetcher.cs:line 119

```

### Workaround 
I can get it to work by [this workaround](https://github.com/mmalvik/puppeteer-sharp/blob/e2ce7bdb858d0e55e1d51ccf455021ee53d0a317/lib/PuppeteerSharp/BrowserData/JsonUtils.cs#L23C9-L30C13) in `JsonUtils`:
```csharp
internal static async Task<string> GetTextAsync(string url)
{
    using var client = new HttpClient();
    var result = await client.GetStringAsync(url).ConfigureAwait(false);
    return result;
}
```
### Versions

* Which version of PuppeteerSharp are you using? `11.0.4`
* Which .NET runtime and version are you targeting? `net6.0`

### Additional Information
My platform is Mac OS when running this. I also get this same issue when running in Azure functions.

**Comment by kblok** [comment]
I was able to reproduce it. That code should work.

**Comment by kblok** [comment]
Fixed on v11.0.5 @mmalvik

**Comment by ogix** [comment]
I get the same error if not specifying `Path` for `BrowserFetcher`.

**Comment by kblok** [comment]
@ogix sorry to hear about that. Can you create a new issue with a code example?
