### ISSUE TITLE
ERR_CONNECTION_TIMED_OUT error while generating a PDF

### ISSUE THREAD

**Issue by frkdrgt** [hardkoded/puppeteer-sharp#2328]
### Description

We are encountering an ERR_CONNECTION_TIMED_OUT error while generating a PDF in a .Net 6 MVC application.

### Complete minimal example reproducing the issue

The codes I tested in the production environment are as follows

E.g.

```csharp
// Arrange
await using var browser = await Puppeteer.LaunchAsync(new LaunchOptions
{
   Headless = true, 
   ExecutablePath = _puppeteerPath,
   IgnoreHTTPSErrors = true,
   Timeout = 0
});
await using var page = await browser.NewPageAsync();
page.DefaultNavigationTimeout = 0;
page.DefaultTimeout = 0;
await page.GoToAsync(url, 0);
await page.WaitForNetworkIdleAsync(); 

var stream = await page.PdfStreamAsync();
await browser.CloseAsync();

return new FileStreamResult(stream, "application/pdf");
```

### Actual behavior:

PuppeteerSharp.NavigationException: net::ERR_CONNECTION_TIMED_OUT at http://MY_URL/e1a69203-c7d9-4ed2-3f43-08dbab0d4d68 at MY_URL/e1a69203-c7d9-4ed2-3f43-08dbab0d4d68
       ---> PuppeteerSharp.NavigationException: net::ERR_CONNECTION_TIMED_OUT at http://MY_URL/e1a69203-c7d9-4ed2-3f43-08dbab0d4d68
         at PuppeteerSharp.FrameManager.NavigateAsync(CDPSession client, String url, String referrer, String referrerPolicy, String frameId) in /home/runner/work/puppeteer-sharp/puppeteer-sharp/lib/PuppeteerSharp/FrameManager.cs:line 209
         at PuppeteerSharp.FrameManager.NavigateFrameAsync(Frame frame, String url, NavigationOptions options) in /home/runner/work/puppeteer-sharp/puppeteer-sharp/lib/PuppeteerSharp/FrameManager.cs:line 81
         --- End of inner exception stack trace ---
         at PuppeteerSharp.FrameManager.NavigateFrameAsync(Frame frame, String url, NavigationOptions options) in /home/runner/work/puppeteer-sharp/puppeteer-sharp/lib/PuppeteerSharp/FrameManager.cs:line 91

### Versions

* PuppeteerSharp 11.0.6
* .NET 6.0

**Comment by kblok** [comment]
`ERR_CONNECTION_TIMED_OUT` comes straight from the browser. I don't know if puppeteer-sharp can do anything about it.
