### ISSUE TITLE
WebSocketException when browser.CloseAsync is called on Visual Studio 2022 and .NET7+ debugging

### ISSUE THREAD

**Issue by eMuonTau** [hardkoded/puppeteer-sharp#2374]
### Description
Visual Studio 2022 breaks on an unhandled WebSocketException when browser.CloseAsync() is called. This only happens on .NET 8. When using .NET 6 there is no exception. I got same exception a few times with .NET 7 but i couldn't reproduce it again. On .NET 8 it happens every time.

Looks like you can continue when this exception is thrown and there is no exception if debugger is not attached. If it is related to Visual Studio please let me know.

```
System.Net.WebSockets.WebSocketException: 'The remote party closed the WebSocket connection without completing the close handshake.'

   at System.Net.WebSockets.ManagedWebSocket.ThrowEOFUnexpected()
   at System.Net.WebSockets.ManagedWebSocket.<EnsureBufferContainsAsync>d__74.MoveNext()
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token) in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/PoolingAsyncValueTaskMethodBuilderT.cs:line 435
   at System.Net.WebSockets.ManagedWebSocket.<ReceiveAsyncPrivate>d__63`1.MoveNext()
```

### Complete minimal example reproducing the issue

```csharp
using System;
using System.IO;
using System.Threading.Tasks;
using PuppeteerSharp;

namespace Namespace;

static class Program
{
  static async Task Main() {
    using var browserFetcher = new BrowserFetcher();
    await browserFetcher.DownloadAsync();
    var browser = await Puppeteer.LaunchAsync(new LaunchOptions() {
      Headless = true,
      UserDataDir = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, ".puppeteer", "chrome")
    });

    try {
      var page = await browser.NewPageAsync();
      await page.GoToAsync("https://google.com");
      await browser.CloseAsync();
    } catch (Exception ex) {
      // WebSocketException is not caught here
      // throw;
    }
    Console.WriteLine("END");
    Console.ReadLine();
  }
}

```

### Expected behavior:

It should not throw an exception.

### Actual behavior:

Debugging breaks on WebSocketException when browser.CloseAsync() is called.

Call Stack
```
[Exception] System.Net.WebSockets.dll!System.Net.WebSockets.ManagedWebSocket.ThrowEOFUnexpected()
[Exception] System.Net.WebSockets.dll!System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(int minimumRequiredBytes, System.Threading.CancellationToken cancellationToken)
System.Private.CoreLib.dll!System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() Line 53
System.Private.CoreLib.dll!System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore<System.Threading.Tasks.VoidTaskResult>.ThrowForFailedGetResult(short token) Line 109
System.Private.CoreLib.dll!System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore<System.Threading.Tasks.VoidTaskResult>.GetResult(short token) Line 95
System.Private.CoreLib.dll!System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder<System.Threading.Tasks.VoidTaskResult>.StateMachineBox<System.Runtime.CompilerServices.IAsyncStateMachine>.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(short token) Line 435
System.Net.WebSockets.dll!System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate<System.Net.WebSockets.WebSocketReceiveResult>(System.Memory<byte> payloadBuffer, System.Threading.CancellationToken cancellationToken)
System.Net.WebSockets.dll!System.Net.WebSockets.ManagedWebSocket.ReceiveAsync(System.ArraySegment<byte> buffer, System.Threading.CancellationToken cancellationToken)
PuppeteerSharp.dll!PuppeteerSharp.Transport.WebSocketTransport.GetResponseAsync(System.Threading.CancellationToken cancellationToken) Line 163
[Resuming Async Method]	
System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<object>.AsyncStateMachineBox<PuppeteerSharp.Transport.WebSocketTransport.<GetResponseAsync>d__25>.ExecutionContextCallback(object s) Line 287
System.Private.CoreLib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state) Line 183
System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<object>.AsyncStateMachineBox<PuppeteerSharp.Transport.WebSocketTransport.<GetResponseAsync>d__25>.MoveNext(System.Threading.Thread threadPoolThread) Line 324
System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<object>.AsyncStateMachineBox<PuppeteerSharp.Transport.WebSocketTransport.<GetResponseAsync>d__25>.MoveNext() Line 302
System.Private.CoreLib.dll!System.Runtime.CompilerServices.TaskAwaiter.OutputWaitEtwEvents.AnonymousMethod__12_0(System.Action innerContinuation, System.Threading.Tasks.Task innerTask) Line 301
System.Private.CoreLib.dll!System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action action, bool allowInlining) Line 743
System.Private.CoreLib.dll!System.Threading.Tasks.Task.RunContinuations(object continuationObject) Line 3417
System.Private.CoreLib.dll!System.Threading.Tasks.Task<System.__Canon>.TrySetResult(System.__Canon result) Line 401
System.Private.CoreLib.dll!System.Threading.Tasks.ValueTask<System.Net.WebSockets.WebSocketReceiveResult>.ValueTaskSourceAsTask..cctor.AnonymousMethod__4_0(object state) Line 649
System.Net.WebSockets.dll!System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate<System.Net.WebSockets.WebSocketReceiveResult>(System.Memory<byte> payloadBuffer, System.Threading.CancellationToken cancellationToken)
[Resuming Async Method]	
System.Private.CoreLib.dll!System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder<System.Net.WebSockets.WebSocketReceiveResult>.StateMachineBox<System.Net.WebSockets.ManagedWebSocket.<ReceiveAsyncPrivate>d__63<System.Net.WebSockets.WebSocketReceiveResult>>.ExecutionContextCallback(object s) Line 393
System.Private.CoreLib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state) Line 183
System.Private.CoreLib.dll!System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder<System.Net.WebSockets.WebSocketReceiveResult>.StateMachineBox<System.Net.WebSockets.ManagedWebSocket.<ReceiveAsyncPrivate>d__63<System.Net.WebSockets.WebSocketReceiveResult>>.MoveNext() Line 415
System.Private.CoreLib.dll!System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder.SetResult() Line 51
System.Net.WebSockets.dll!System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(int minimumRequiredBytes, System.Threading.CancellationToken cancellationToken)
[Resuming Async Method]	
System.Private.CoreLib.dll!System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder<System.Threading.Tasks.VoidTaskResult>.StateMachineBox<System.Net.WebSockets.ManagedWebSocket.<EnsureBufferContainsAsync>d__74>.ExecutionContextCallback(object s) Line 393
System.Private.CoreLib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state) Line 183
System.Private.CoreLib.dll!System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder<System.Threading.Tasks.VoidTaskResult>.StateMachineBox<System.Net.WebSockets.ManagedWebSocket.<EnsureBufferContainsAsync>d__74>.MoveNext() Line 415
System.Private.CoreLib.dll!System.IO.Stream.ReadAtLeastAsyncCore(System.Memory<byte> buffer, int minimumBytes, bool throwOnEndOfStream, System.Threading.CancellationToken cancellationToken) Line 450
[Resuming Async Method]	
System.Private.CoreLib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state) Line 183
System.Private.CoreLib.dll!System.Runtime.CompilerServices.TaskAwaiter.OutputWaitEtwEvents.AnonymousMethod__12_0(System.Action innerContinuation, System.Threading.Tasks.Task innerTask) Line 301
System.Private.CoreLib.dll!System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action action, bool allowInlining) Line 743
System.Private.CoreLib.dll!System.Threading.Tasks.Task.RunContinuations(object continuationObject) Line 3417
System.Private.CoreLib.dll!System.Threading.Tasks.Task<int>.TrySetResult(int result) Line 401
System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<int>.SetExistingTaskResult(System.Threading.Tasks.Task<int> task, int result) Line 446
[Completed] System.Net.Http.dll!System.Net.Http.HttpConnection.RawConnectionStream.ReadAsync(System.Memory<byte> buffer, System.Threading.CancellationToken cancellationToken) Line 88
System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<int>.AsyncStateMachineBox<System.Net.Http.HttpConnection.RawConnectionStream.<ReadAsync>d__6>.ExecutionContextCallback(object s) Line 287
System.Private.CoreLib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state) Line 183
System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<int>.AsyncStateMachineBox<System.Net.Http.HttpConnection.RawConnectionStream.<ReadAsync>d__6>.MoveNext(System.Threading.Thread threadPoolThread) Line 324
System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<int>.AsyncStateMachineBox<System.Net.Http.HttpConnection.RawConnectionStream.<ReadAsync>d__6>.MoveNext() Line 302
System.Private.CoreLib.dll!System.Runtime.CompilerServices.TaskAwaiter.OutputWaitEtwEvents.AnonymousMethod__12_0(System.Action innerContinuation, System.Threading.Tasks.Task innerTask) Line 301
System.Private.CoreLib.dll!System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action action, bool allowInlining) Line 743
System.Private.CoreLib.dll!System.Threading.Tasks.Task.RunContinuations(object continuationObject) Line 3417
System.Private.CoreLib.dll!System.Threading.Tasks.Task<int>.TrySetResult(int result) Line 401
System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<int>.SetExistingTaskResult(System.Threading.Tasks.Task<int> task, int result) Line 446
[Completed] System.Net.Http.dll!System.Net.Http.HttpConnection.ReadBufferedAsyncCore(System.Memory<byte> destination) Line 1877
System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<int>.AsyncStateMachineBox<System.Net.Http.HttpConnection.<ReadBufferedAsyncCore>d__105>.ExecutionContextCallback(object s) Line 287
System.Private.CoreLib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state) Line 183
System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<int>.AsyncStateMachineBox<System.Net.Http.HttpConnection.<ReadBufferedAsyncCore>d__105>.MoveNext(System.Threading.Thread threadPoolThread) Line 324
System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<int>.AsyncStateMachineBox<System.Net.Http.HttpConnection.<ReadBufferedAsyncCore>d__105>.MoveNext() Line 302
System.Net.Sockets.dll!System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.InvokeContinuation(System.Action<object> continuation, object state, bool forceAsync, bool requiresExecutionContextFlow)
System.Net.Sockets.dll!System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.OnCompleted(System.Net.Sockets.SocketAsyncEventArgs _)
System.Net.Sockets.dll!System.Net.Sockets.SocketAsyncEventArgs..cctor.AnonymousMethod__176_0(uint errorCode, uint numBytes, System.Threading.NativeOverlapped* nativeOverlapped)
System.Private.CoreLib.dll!System.Threading.PortableThreadPool.IOCompletionPoller.Callback.Invoke(System.Threading.PortableThreadPool.IOCompletionPoller.Event e) Line 265
System.Private.CoreLib.dll!System.Threading.ThreadPoolTypedWorkItemQueue<System.Threading.PortableThreadPool.IOCompletionPoller.Event, System.Threading.PortableThreadPool.IOCompletionPoller.Callback>.System.Threading.IThreadPoolWorkItem.Execute() Line 1143
System.Private.CoreLib.dll!System.Threading.ThreadPoolWorkQueue.Dispatch() Line 924
System.Private.CoreLib.dll!System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart() Line 121
```

### Versions

* PuppeteerSharp: 9.1.0 - 13.0.2
* .NET: 8.0
* Visual Studio 2022: 17.8.3

**Comment by kblok** [comment]
Do you have [VS set to break on all exceptions](https://learn.microsoft.com/en-us/visualstudio/debugger/managing-exceptions-with-the-debugger?view=vs-2022)? That [piece of code has a try/catch](https://github.com/hardkoded/puppeteer-sharp/blob/master/lib/PuppeteerSharp/Transport/WebSocketTransport.cs#L161).

**Comment by eMuonTau** [comment]
> Do you have [VS set to break on all exceptions](https://learn.microsoft.com/en-us/visualstudio/debugger/managing-exceptions-with-the-debugger?view=vs-2022)? That [piece of code has a try/catch](https://github.com/hardkoded/puppeteer-sharp/blob/master/lib/PuppeteerSharp/Transport/WebSocketTransport.cs#L161).

Exception Settings are on default. WebSocketException is not even selected in CLR Exceptions and dialog indicates to break only when user-unhandled.

![2023-12-12_01h31_17](https://github.com/hardkoded/puppeteer-sharp/assets/5517365/386730cb-44cc-425f-a940-214f00d440d3)

**Comment by kblok** [comment]
@eMuonTau I think the issue is with the second checkbox you have there.

**Comment by JohnPicchi** [comment]
Oddly for me, I was getting the same error inside Rider 2024.2 but not inside Visual Studio 2022. I resolved the issue by disabling 'external source debug' in Rider (File > Settings > Build, Execution, Deployment), this setting is enabled by default. The corresponding setting in Visual Studio is 'Enable Just My Code' (Tools > Options > Debugging).

**Comment by joseborges** [comment]
I still have this problem in 2025? 

Exception thrown: 'System.Net.WebSockets.WebSocketException' in System.Net.WebSockets.dll
Exception thrown: 'System.Net.WebSockets.WebSocketException' in System.Private.CoreLib.dll
Exception thrown: 'System.Net.WebSockets.WebSocketException' in System.Net.WebSockets.dll
Exception thrown: 'System.Net.WebSockets.WebSocketException' in System.Private.CoreLib.dll
Exception thrown: 'System.Net.WebSockets.WebSocketException' in System.Private.CoreLib.dll
Exception thrown: 'System.TimeoutException' in PuppeteerSharp.dll
Exception thrown: 'System.TimeoutException' in System.Private.CoreLib.dll
The thread '.NET Long Running Task' (27384) has exited with code 0 (0x0).

Isn't there a fix in version 20.1.3 for the error reported?
