### ISSUE TITLE
CDPSession issue with StackTrace

### ISSUE THREAD

**Issue by crystalgreen** [hardkoded/puppeteer-sharp#2496]
I use PuppeteerSharp with my PWA web app. That also executes the JS: `console.info('text')`. This becomes important later...
Since update to PuppeteerSharp v14.1.0 (.NET 8) I get the following issue.
After `page.GoToPageAsync(...)` the `page.Client.IsClosed == true` with 
`CloseReason`:

```
Page failed to process Runtime.consoleAPICalled. Error reading string. Unexpected token: StartObject. Path 'stackTrace.parentId'..    at Newtonsoft.Json.JsonReader.ReadAsString()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject[T](JsonSerializer jsonSerializer)
   at PuppeteerSharp.Helpers.Json.JTokenExtensions.ToObject[T](JToken token, JsonSerializerSettings jsonSerializerSettings) in D:\work\Playground\cs\puppeteer-sharp\lib\PuppeteerSharp\Helpers\Json\JTokenExtensions.cs:line 41
   at PuppeteerSharp.Helpers.Json.JTokenExtensions.ToObject[T](JToken token, Boolean camelCase) in D:\work\Playground\cs\puppeteer-sharp\lib\PuppeteerSharp\Helpers\Json\JTokenExtensions.cs:line 23
   at PuppeteerSharp.Page.Client_MessageReceived(Object sender, MessageEventArgs e) in D:\work\Playground\cs\puppeteer-sharp\lib\PuppeteerSharp\Page.cs:line 1474
```

This causes other issues down the line so my _puppeteering_ of that page cannot continue.

Unfortunately, I haven't be able to isolate the issue in a small demo app/test. But I managed to find the reason and a possible fix.
In [CDPSession.OnMessage](https://github.com/hardkoded/puppeteer-sharp/blob/master/lib/PuppeteerSharp/CDPSession.cs#L145), the `obj.Params` that causes the problem is:

```json
{
  "type": "info",
  "args": [
    {
      "type": "string",
      "value": "text"
    }
  ],
  "executionContextId": 3,
  "timestamp": 1710319875440.503,
  "stackTrace": {
    "callFrames": [
      {
        "functionName": "log",
        "scriptId": "9",
        "url": "https://localhost:5001/js/app.5a5e1f5a.js",
        "lineNumber": 3283,
        "columnNumber": 24
      }
    ],
    "parentId": {
      "id": "19"
    }
  }
}
```

This message corresponds to the above mentioned `console.info` call.
To find that message, I set a conditional breakpoint on the above linked line in `CDPSession` with condition `obj.Params["stackTrace"]!=null`.

The problem is that `parentId` is an object with an inner id field but it is mapped to the PuppeteerSharp [StackTrace](https://github.com/hardkoded/puppeteer-sharp/blob/master/lib/PuppeteerSharp/Messaging/StackTrace.cs#L11) class with public `string ParentId { get; set; }`. I found the [DevTools Protocol doc for StackTrace](https://chromedevtools.github.io/devtools-protocol/tot/Runtime/#type-StackTrace) and it confirms that structure. One possible fix could be to adopt that structure or to use `Newtonsoft.Json.Linq.JToken` instead of string as type. That fixed the issue for me.

In my attempts to reproduce the issue outside my app, I never got that `parentId` field and don't know how to get it. I see that log calls create a `stackTrace` structure but without that field.
I tried modifying your test `ShouldHaveLocationForConsoleAPICalls` and `consolelog.html` but couldn't reproduce it.

In my tests I used Chrome for testing `121.0.6167.85`. But this version works also with the old PuppeteerSharp 13.0.2, so I don't think this is because of a change in the Chrome version.

**Comment by kblok** [comment]
Thank you for reporting this @crystalgreen.
I'm shipping a new version today.
