### ISSUE TITLE
generate pdf lambda

### ISSUE THREAD

**Issue by satviktechie1986** [hardkoded/puppeteer-sharp#2806]
var browserLauncher = new HeadlessChromiumPuppeteerLauncher(new LoggerFactory().AddSerilog(Log.Logger));
 await using (var browser = await browserLauncher.LaunchAsync())
 {
     await using var page = await browser.NewPageAsync();
     await page.GoToAsync("http://www.google.com"); // In case of fonts being loaded from a CDN, use WaitUntilNavigation.Networkidle0 as a second param.
     await page.EvaluateExpressionHandleAsync("document.fonts.ready"); // Wait for fonts to be loaded. Omitting this might result in no text rendered in pdf.
     context.Logger.LogInformation("EvaluateExpressionHandleAsync ");
     var result = await page.PdfStreamAsync();
     var fileTransferUtility = new TransferUtility(S3Client);
     await fileTransferUtility.UploadAsync(result, report.BucketName, s3ObjectKey);
 }
 
 
 Error : 

2024-10-25T10:00:32.575Z	266420e0-161e-4a1f-a3ec-ae6369c1238e	info	PuppeteerSharp.ProcessException: Failed to launch browser! /tmp/chromium: error while loading shared libraries: libnspr4.so: cannot open shared object file: No such file or directory

   at PuppeteerSharp.States.ProcessStartingState.StartCoreAsync(LauncherBase p) in /home/runner/work/puppeteer-sharp/puppeteer-sharp/lib/PuppeteerSharp/States/ProcessStartingState.cs:line 83
   at PuppeteerSharp.States.ProcessStartingState.StartCoreAsync(LauncherBase p) in /home/runner/work/puppeteer-sharp/puppeteer-sharp/lib/PuppeteerSharp/States/ProcessStartingState.cs:line 89
   at PuppeteerSharp.Launcher.LaunchAsync(LaunchOptions options) in /home/runner/work/puppeteer-sharp/puppeteer-sharp/lib/PuppeteerSharp/Launcher.cs:line 72
   at PuppeteerSharp.Launcher.LaunchAsync(LaunchOptions options) in /home/runner/work/puppeteer-sharp/puppeteer-sharp/lib/PuppeteerSharp/Launcher.cs:line 105
   at HeadlessChromium.Puppeteer.Lambda.Dotnet.HeadlessChromiumPuppeteerLauncher.LaunchAsync(String[] chromeArgs)
   at PIB.DocumentGenerator.Data.Services.DocumentProcessService.GeneratePdfTest(ReportModel report, ILambdaContext context) in /home/vsts/work/1/s/PIB.DocumentGenerator.Data/Services/DocumentProcessService.cs:line 346

**Comment by kblok** [comment]
I  would start by looking at how to install Chrome in lambda first.

**Comment by satviktechie1986** [comment]
> I would start by looking at how to install Chrome in lambda first.

okay 
Thanks for your reply
